name: artbyrobin
favicon: null
layout_spectrum: 0.51053
typography_spectrum: 0.50572
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9a1f1a'
    - '#de6a2d'
    - '#1d1b21'
    - '#b69858'
    - '#557b8d'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
