favicon: null
name: artbyrobin
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 1
  lightness: 0.6875
  brandColors:
    - '#a51e24'
    - '#ffffff'
    - '#f37123'
    - '#6279bc'
    - '#b9b935'
  rhythmicContrast: 1
typography_spectrum: 0.50572
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.87658
analytics:
  twitter: null
  google: null
  facebook: null
