favicon: null
name: artbyrobin
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 0
  lightness: 0.4498208
  brandColors:
    - '#0E0C0C'
    - '#906F42'
    - '#C5B4AC'
    - '#FFFBE9'
    - '#BD0C28'
  rhythmicContrast: 0.4928315
typography_spectrum: 0.301855
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
