typography_spectrum: 0.301855
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
purpose: []
color:
  saturation: 0.2048904
  brandStrength: 0
  rhythmicContrast: 0.801855
  brandColors:
    - '#0E0C0C'
    - '#906F42'
    - '#C5B4AC'
    - '#FFFBE9'
    - '#BD0C28'
  lightness: 1
favicon: null
name: artbyrobin
analytics:
  twitter: null
  google: null
  facebook: null
