layout_spectrum: 1
favicon: null
name: artbyrobin
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  bucket: null
  version: null
  domain: null
color:
  brandStrength: 1
  lightness: 0.3001686
  saturation: 0.3718381
  rhythmicContrast: 0.4637437
  brandColors:
    - '#E2CFBC'
    - '#878689'
    - '#150E0E'
    - '#6D5C53'
    - '#C67766'
typography_spectrum: 0.301855
