layout_spectrum: 1
favicon: null
name: artbyrobin
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.8507589
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
  brandColors:
    - '#0E0C0C'
    - '#906F42'
    - '#C5B4AC'
    - '#FFFBE9'
    - '#BD0C28'
typography_spectrum: 0.301855
